./test.sh  | egrep "(Running|Time elapsed)"
echo ""
echo ""
./test.sh  | egrep "(Running|Time elapsed)"
echo ""
echo ""
./test.sh  | egrep "(Running|Time elapsed)"
echo ""
echo ""
./test.sh  | egrep "(Running|Time elapsed)"
echo ""
echo ""
./test.sh  | egrep "(Running|Time elapsed)"
echo ""
echo ""
