./test.sh  | egrep "(Running|Time elapsed|Bean took)"
echo ""
echo ""
./test.sh  | egrep "(Running|Time elapsed|Bean took)"
echo ""
echo ""
./test.sh  | egrep "(Running|Time elapsed|Bean took)"
echo ""
echo ""
./test.sh  | egrep "(Running|Time elapsed|Bean took)"
echo ""
echo ""
./test.sh  | egrep "(Running|Time elapsed|Bean took)"
echo ""
echo ""
